### ISSUE TITLE
Docker run args

### ISSUE THREAD

**Issue by mrares** [eremetic-framework/eremetic#118]
Consider accepting and forwarding port and network args to the containerizer, some tasks might want to expose ports or bind to particular networks

**Comment by keis** [comment]
It's something we would want to support eventually. We have no intimidate need but PRs are of course welcome :)

**Comment by mrares** [comment]
Well, then... https://github.com/klarna/eremetic/pull/119

**Comment by atl893** [comment]
I'll jump on this because it's related:

So I thought the attached PR was gonna fix my problem, but I was misunderstanding what the I was reading, and it doesn't work as I thought. 

Basically I need to forward some ports to the docker container that I can then bind to internally so that when it broadcasts it communicates externally it can pass those ports through to other clients. 

So I either need a way to specify host networking like marathon has and just try to bind to random ports(which the software in question has support for), be able to bind ports on the host to specific ports(ie -p 9050:9050 in docker) or be able to ask for the mesos random ports and have them bind to themselves(ie if the port definition was {"container_port": 0,"protocol": "tcp" }, I could just tell the program to bind to $PORT0).

**Comment by keis** [comment]
Either of those except host networking should work now. Are you running into some problem?

I think the easiest way to use is to set container_port=9050 which will let mesos pick a available port while the container still listens on 9050 regardless. You can then use $PORT0 to tell other components where to find you.

**Comment by atl893** [comment]
The problem with that is that the program itself(Spark) launches tasks inside mesos and tells the tasks what ports to connect back to the master, which are the internal bound ports not the mesos ephemeral.

I could try and patch spark to pass through the external ports, as advertised ports, but that is going to be much harder than if eremetic could either attempt to bind the docker container to the same port as the container port, or if it allowed the allocation of random mesos ports that bound to themselves that I could then tell spark to use.

**Comment by keis** [comment]
So you are trying to run spark with eremetic? Not to discourage you or anything but why not use marathon/aurora for that? I think that would be a better fit if you're running it as a persistent service.

Anyway, setting container_port=0 should make eremetic allocate a random port that your container can listen on. I have not tried the port support myself yet but I think that should just work.

**Comment by atl893** [comment]
We actually do largely run spark via marathon, but our data scientists
write a lot of development code in Python which is not supported for
launching the driver portion of Python in the way supported by
marathon/mesos but can launch executors in mesos.

So therefore I am trying to come up with a solution to use mesos resources
to launch the Python drivers so that I can get them away from running it
locally.

I have tried to set container_port=0 but it doesn't seem to allocate the
ports, at least not when I look at the docker invocation.

**Comment by keis** [comment]
Ok. interesting. I'm not super familiar with spark but I guess this means you have temporary framework for the duration of some computation? Sounds pretty reasonable to me :)

Did a quick look at the code and it looks like for container_port=0 we don't actually map a port. but we do skip ahead in the range so we might allocate it. I think this is simply a bug. @alde @marcusolsson thoughts?

**Comment by atl893** [comment]
Yeah, I should clarify that the ports are allocated it seems as they show up as env variables, but that they are not part of the docker invocation that the mesos docker containerizer uses.

**Comment by keis** [comment]
@atl893 Tagged a new release 0.26.0 that should resolve this issue :)
