### ISSUE TITLE
Privileged Docker container

### ISSUE THREAD

**Issue by petr-k** [eremetic-framework/eremetic#167]
Maybe I'am missing something, but I can't seem to figure out how to run a Docker container task with the `--privileged` flag.

It this something that is not supported by design?

**Comment by keis** [comment]
Hi @petr-k 

You're correct there's no flag to enable privileged mode in the api. This is not because it's a bad idea and we don't want to support it but because we have by design omitted everything we don't need until we need it. YAGNI :)

Still, running in privileged mode is best to avoid if you can. But if for some reason you can't I would be happy to accept a PR adding a, default false, flag for this.

**Comment by heww** [comment]
@petr-k  try  https://hub.docker.com/r/heww/eremetic/  it add privileged support for eremetic

**Comment by keis** [comment]
Added in #183
